// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartScout.Infrastructure.Data;

#nullable disable

namespace SmartScout.Infrastructure.Migrations
{
    [DbContext(typeof(SmartScoutDbContext))]
    [Migration("20261005195314_AddPlayerSeasonStats")]
    partial class AddPlayerSeasonStats
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartScout.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ExternalApiId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Height")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TeamName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("WeightPounds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExternalApiId")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("SmartScout.Domain.Entities.PlayerSeasonStat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Assists")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Blocks")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Fg3Pct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FgPct")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FtPct")
                        .HasColumnType("numeric");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<string>("Minutes")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Points")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Rebounds")
                        .HasColumnType("numeric");

                    b.Property<int>("Season")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Steals")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Turnovers")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("SeasonStats");
                });

            modelBuilder.Entity("SmartScout.Domain.Entities.PlayerSeasonStat", b =>
                {
                    b.HasOne("SmartScout.Domain.Entities.Player", "Player")
                        .WithMany("SeasonStats")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("SmartScout.Domain.Entities.Player", b =>
                {
                    b.Navigation("SeasonStats");
                });
#pragma warning restore 612, 618
        }
    }
}
